# Generated by Django 6.1 on 2026-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('report_date', models.DateField(help_text="Same date you'd pass as report_date to processor.process(). Year/month for persist_to_database() are derived from this automatically.")),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('filtered_file', models.FileField(blank=True, null=True, upload_to='filtered/')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('filtered_row_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
