# Generated by Django 6.1 on 2026-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='filter_private',
            field=models.BooleanField(default=True, help_text='If checked, the filtered output / SQL Server push only includes rows where License Type resolves to Private. Uncheck to keep all license types in the filtered output.'),
        ),
    ]
